# LSTM-AE PSM Anomaly Detection Configuration

# Task configuration
task_name: anomaly_detection
is_training: 1
is_inference: 0
model: LSTM_AE

# Data configuration
data: PSM
root_path: ./datasets/PSM/
data_path: train.csv
features: M
target: OT
freq: h
checkpoints: ./checkpoints/

# Sequence configuration
seq_len: 100
label_len: 50
pred_len: 1

# Model architecture
enc_in: 25
dec_in: 25
c_out: 25
d_model: 128
n_heads: 8
e_layers: 2
d_layers: 1
d_ff: 512
moving_avg: 25
factor: 3
distil: true
dropout: 0.1
embed: timeF
activation: gelu

# Training configuration
num_workers: 8
itr: 1
train_epochs: 10
batch_size: 32
patience: 5
learning_rate: 0.001
loss: MSE
lradj: type1
use_amp: false

# Hardware configuration
use_gpu: true
gpu: 0
gpu_type: cuda
use_multi_gpu: false
devices: "0,1,2,3"

# Other settings
seed: 2021
use_dtw: false
use_tqdm: true
use_wandb: false
inverse: false
scale: true
time_encoding: true
auto_feature_dims: false

# Anomaly detection specific
anomaly_ratio: 0.25
win_size: 100
threshold_method: percentile
